default: &default
  adapter: postgresql
  encoding: unicode
  user: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: bottopia_development

test:
  <<: *default
  database: bottopia_test

production:
  <<: *default
  database: bottopia_production
  username: bottopia
  password: <%= ENV['BOTTOPIA_DATABASE_PASSWORD'] %>
